//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddrBook.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AddrBookContext : DbContext
    {
        public AddrBookContext()
            : base("name=AddrBookContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ContactsInfo> ContactsInfo { get; set; }
        public DbSet<DetailInfo> DetailInfo { get; set; }
        public DbSet<GroupInfo> GroupInfo { get; set; }
        public DbSet<RecordInfo> RecordInfo { get; set; }
    }
}
